services:
  - type: web
    name: fastapi-backend
    runtime: python
    region: India
    buildCommand: ""  # No build step needed
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
    plan: free
